kind: pipeline
name: mariadb10.0-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mariadb10.0-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mariadb

services:
- name: cache
  image: redis
- name: mariadb
  image: mariadb:10.0
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mariadb10.1-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mariadb10.1-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mariadb

services:
- name: cache
  image: redis
- name: mariadb
  image: mariadb:10.1
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mariadb10.2-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mariadb10.2-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mariadb

services:
- name: cache
  image: redis
- name: mariadb
  image: mariadb:10.2
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mariadb10.3-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mariadb10.3-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mariadb

services:
- name: cache
  image: redis
- name: mariadb
  image: mariadb:10.3
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mariadb10.4-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mariadb10.4-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mariadb

services:
- name: cache
  image: redis
- name: mariadb
  image: mariadb:10.4
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mysql8.0-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mysql-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysql

services:
- name: cache
  image: redis
- name: mysql
  image: mysql:8.0
  command: [ "--default-authentication-plugin=mysql_native_password", "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mysql5.7-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mysql-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysql

services:
- name: cache
  image: redis
- name: mysql
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mysql5.7-php7.2

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mysql-php7.2
  image: nextcloudci/php7.2:php7.2-12
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysql

services:
- name: mysql
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mysql5.7-php7.3

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mysql-php7.3
  image: nextcloudci/php7.3:php7.3-1
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysql

services:
- name: mysql
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mysql5.6-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mysql5.6-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysql

services:
- name: cache
  image: redis
- name: mysql
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mysql5.5-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mysql5.5-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysql

services:
- name: cache
  image: redis
- name: mysql
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: postgres9-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: postgres-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - sleep 10 # gives the database enough time to initialize
    - POSTGRES=9 NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql

services:
- name: cache
  image: redis
- name: postgres-9
  image: postgres:9
  environment:
    POSTGRES_USER: oc_autotest
    POSTGRES_DB: oc_autotest_dummy
    POSTGRES_PASSWORD: owncloud
  tmpfs:
    - /var/lib/postgresql/data

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: postgres10-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: postgres-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - sleep 10 # gives the database enough time to initialize
    - POSTGRES=10 NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql

services:
- name: cache
  image: redis
- name: postgres-10
  image: postgres:10
  environment:
    POSTGRES_USER: oc_autotest
    POSTGRES_DB: oc_autotest_dummy
    POSTGRES_PASSWORD: owncloud
  tmpfs:
    - /var/lib/postgresql/data

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: postgres11-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: postgres-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - sleep 10 # gives the database enough time to initialize
    - POSTGRES=11 NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql

services:
- name: cache
  image: redis
- name: postgres-11
  image: postgres:11
  environment:
    POSTGRES_USER: oc_autotest
    POSTGRES_DB: oc_autotest_dummy
    POSTGRES_PASSWORD: owncloud
  tmpfs:
    - /var/lib/postgresql/data

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mysqlmb4-php7.1

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mysqlmb4-php7.1
  image: nextcloudci/php7.1:php7.1-16
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysqlmb4

services:
- name: cache
  image: redis
- name: mysqlmb4
  image: mysql:5.7.22
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--innodb_large_prefix=true", "--innodb_file_format=barracuda", "--innodb_file_per_table=true", "--innodb-buffer-pool-size=512M", "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mysqlmb4-php7.2

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mysqlmb4-php7.2
  image: nextcloudci/php7.2:php7.2-12
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysqlmb4

services:
- name: cache
  image: redis
- name: mysqlmb4
  image: mysql:5.7.22
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--innodb_large_prefix=true", "--innodb_file_format=barracuda", "--innodb_file_per_table=true", "--innodb-buffer-pool-size=512M", "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: mysqlmb4-php7.3

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: mysqlmb4-php7.3
  image: nextcloudci/php7.3:php7.3-1
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysqlmb4

services:
- name: cache
  image: redis
- name: mysqlmb4
  image: mysql:5.7.22
  environment:
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: oc_autotest
    MYSQL_PASSWORD: owncloud
    MYSQL_DATABASE: oc_autotest
  command: [ "--innodb_large_prefix=true", "--innodb_file_format=barracuda", "--innodb_file_per_table=true", "--innodb-buffer-pool-size=512M", "--max_allowed_packet=128M", "--wait_timeout=28800", "--log-error-verbosity=3", "--log-error=/dev/stdout", "--general-log-file=/dev/stdout", "--general-log"]
  tmpfs:
    - /var/lib/mysql

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
